spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: platzi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # create-drop se utiliza la primera vez para crear la estructura de la bd, después se utiliza update
    generate-ddl: true  # Imprime la instrucción SQL relacionada al método, ya sea save() o update().
    show-sql: true
  # security:  # Se encuentran definidas en BasicConfiguration.java
    # user:
      # name: cesar
      # password: platzi
